### ISSUE TITLE
Does Not Follow Sponge Economy Plugin Best Practices

### ISSUE THREAD

**Issue by williamhatcher** [DosMike/VillagerShops#24]
When trying to buy from a shop, money is not taken out of my inventory, and this error is outputted to the console.
```
[19:42:07 ERROR] [Sponge]: Could not pass ClickInventoryEvent$Primary$Impl to Plugin{id=vshop, name=VillagerShops, version=1.5.1, description=Set up Mobs of any type as admin shop. Shops will use a Inventory-Menu to buy/sell items, url=https://github.com/DosMike/VillagerShops, authors=[DosMike], source=mods\VillagerShops.jar}
java.lang.IllegalArgumentException: null
        at flavor.pie.pieconomy.util.kludge.InventoriesKt.get(inventories.kt:50) ~[InventoriesKt.class:?]
        at flavor.pie.pieconomy.PieconomyPlayerAccount.getBalance(PieconomyPlayerAccount.kt:43) ~[PieconomyPlayerAccount.class:?]
        at org.spongepowered.api.service.economy.account.Account.getBalance(Account.java:143) ~[Account.class:1.12.2-7.1.0-BETA-5]
        at de.dosmike.sponge.vshop.StockItem.canAfford(StockItem.java:192) ~[StockItem.class:?]
        at de.dosmike.sponge.vshop.StockItem.buy(StockItem.java:209) ~[StockItem.class:?]
        at de.dosmike.sponge.vshop.InteractionHandler.shopItemClicked(InteractionHandler.java:100) ~[InteractionHandler.class:?]
        at de.dosmike.sponge.vshop.InteractionHandler.clickInventory(InteractionHandler.java:65) ~[InteractionHandler.class:?]
        at de.dosmike.sponge.vshop.ShopInventoryListener.accept(ShopInventoryListener.java:52) ~[ShopInventoryListener.class:?]
        at de.dosmike.sponge.vshop.ShopInventoryListener.accept(ShopInventoryListener.java:1) ~[ShopInventoryListener.class:?]
        at org.spongepowered.common.item.inventory.custom.CustomInventoryListener.handle(CustomInventoryListener.java:54) ~[CustomInventoryListener.class:1.12.2-7.1.0-BETA-5]
        at org.spongepowered.common.item.inventory.custom.CustomInventoryListener.handle(CustomInventoryListener.java:36) ~[CustomInventoryListener.class:1.12.2-7.1.0-BETA-5]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.12.2-7.1.0-BETA-5]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:403) [SpongeEventManager.class:1.12.2-7.1.0-BETA-5]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:430) [SpongeEventManager.class:1.12.2-7.1.0-BETA-5]
        at org.spongepowered.common.event.SpongeEventManager.post(SpongeEventManager.java:422) [SpongeEventManager.class:1.12.2-7.1.0-BETA-5]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:207) [SpongeImpl.class:1.12.2-7.1.0-BETA-5]
        at org.spongepowered.common.event.tracking.phase.packet.BasicInventoryPacketState.unwind(BasicInventoryPacketState.java:201) [BasicInventoryPacketState.class:1.12.2-7.1.0-BETA-5]
        at org.spongepowered.common.event.tracking.phase.packet.BasicInventoryPacketState.unwind(BasicInventoryPacketState.java:55) [BasicInventoryPacketState.class:1.12.2-7.1.0-BETA-5]
        at org.spongepowered.common.event.tracking.PhaseTracker.completePhase(PhaseTracker.java:233) [PhaseTracker.class:1.12.2-7.1.0-BETA-5]
        at org.spongepowered.common.event.tracking.PhaseContext.close(PhaseContext.java:399) [PhaseContext.class:1.12.2-7.1.0-BETA-5]
        at org.spongepowered.common.network.PacketUtil.onProcessPacket(PacketUtil.java:151) [PacketUtil.class:1.12.2-7.1.0-BETA-5]
        at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zkh000(SourceFile:539) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:274) [SpongeImplHooks.class:1.12.2-7.1.0-BETA-5]
        at net.minecraft.server.MinecraftServer.redirect$onRun$zim000(SourceFile:4179) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(SourceFile:1523) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(SourceFile:349) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(SourceFile:560) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(SourceFile:464) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
```

Versions Used: 
JAVA 8
SpongeVanilla version 1.12.2-7.1.0-BETA-5
Minecraft 1.12.2
Pieconomy 0.5.0
LangSwitch 1.1.2VillagerShops 1.5.1

**Comment by williamhatcher** [comment]
Somewhat fixed with Pieconomy 0.5.1

However, When you sell items back, your bal does not go up.

**Comment by pie-flavor** [comment]
This is definitely a problem with your plugin. You do not check any of the results of the transactions you create. As such, if you get `ACCOUNT_NO_SPACE` or `ACCOUNT_NO_FUNDS`, you wouldn't know it. You're also making blind assumptions about an account's ability to have funds withdrawn or deposited based on the account's balance, which the docs explicitly say not to do.

**Comment by DosMike** [comment]
@pie-flavor thanks for the hints.

I probably won't get around to look into this until mid February tho

**Comment by williamhatcher** [comment]
For reference, here's the link to [Sponge's Economy API Best Practices](https://docs.spongepowered.org/stable/en/plugin/economy/practices.html).

**Comment by DosMike** [comment]
I think if I wan't to do this the right way I need to detect how many of the item can be added to the inventory - can I use query on the player inventory for this?

**Comment by pie-flavor** [comment]
That's one of the things, but the primary thing you need to do to work with economy plugins is check the return values on `deposit` and `withdraw`.
And no, you can't. I had the number of items ahead of time, so mine was simpler - iterate through the items; add them to the inventory and check the result; store each successfully added item in a list; if it fails, go through the list and remove the items from the inventory before reporting failure.

**Comment by pie-flavor** [comment]
Seems like you've got the first part.
