### ISSUE TITLE
Possible Problem with the current sponge-Version 1.12.2-2705-7.1.0-BETA-3458

### ISSUE THREAD

**Issue by Husky110** [DosMike/VillagerShops#47]
Hello,

As stated in the title, I'm running vshops on Sponge-Forge Version 1.12.2-2705-7.1.0-BETA-3458 with Forge-Version 1.12.2-14.23.4.2760. I've made myself a Lobby-World which is a custom-built void-world. Whenever I create a shop with /vshop create minecraft:villager Engineering it spawn, but blinks wildly. When I try to delete it, it throws an error: 
`[11:19:43] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'vshop delete' for source EntityPlayerMP['Husky110'/145, l='LobbyWorld', x=-7.14, y=9.00, z=50.47]: null
java.lang.NullPointerException: null
at de.dosmike.sponge.vshop.CommandRegistra$4.execute(CommandRegistra.java:355) ~[CommandRegistra$4.class:?]
at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) ~[ChildCommandElementExecutor.class:1.12.2-2705-7.1.0-BETA-3458]
at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2705-7.1.0-BETA-3458]
at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:341) ~[SimpleDispatcher.class:1.12.2-2705-7.1.0-BETA-3458]
at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334) [SpongeCommandManager.class:1.12.2-2705-7.1.0-BETA-3458]
at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083) [dh.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:958) [pa.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:937) [pa.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193) [PacketPhaseUtil.class:1.12.2-2705-7.1.0-BETA-3458]
at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlf000(SourceFile:539) [hv$1.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_151]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_151]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:294) [SpongeImplHooks.class:1.12.2-2705-7.1.0-BETA-3458]
at net.minecraft.server.MinecraftServer.redirect$onRun$zjj000(MinecraftServer.java:3970) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]`
Making the shops complete unuseable... Could you please look into this?

**Comment by DosMike** [comment]
Do you know if mob spawning is disabled or blocked in that area?

**Comment by Husky110** [comment]
well in that dimension doMobSpawn is set to false, but it worked before when I tested it...

**Comment by Husky110** [comment]
I've tested it in another dimension (regular overworld) aswell, same effect... Log doesn't provide more intel on this - sorry...

**Comment by DosMike** [comment]
OK, can you please attach the list of plugins/mods you're using, so i can take a look at it.

As for what the blinking usually means: VillagerShop tries to spawn Shop-Mob that went missing on a timer. It seems that some kind of protection or limitation (keeping chunk entity limits in mind) blocks the Mob from spawning by deleting it right at the next tick. That of course causes VillagerShop to loose track of a Shop-Mob and it tries to spawn in a new one.

**Comment by Husky110** [comment]
Sure:

- Aliases-1.0
- Chisel-MC1.12.2-0.2.1.35
- CodeChickenLib-1.12.2-3.2.2.353-universal
- CoFHCore-1.12.2-4.5.3.20-universal
- CoFHWorld-1.12.2-1.2.0.5-universal
- CraftTweaker2-1.12-4.1.9
- CTMLib-MC1.7.10-1.4.1.5
- Decocraft-2.6.1_1.12.2
- EconomyLite-7.1.0-2.15.1
- ItemBlacklist-1.4.0
- jei_1.12.2-4.11.0.212
- LangSwitch-1.2
- LuckPerms-Sponge-4.2.98
- NoPortal-1.0.0
- PlotSquared-Sponge-18.09.09-eab918b-2040
- projectcore-7.0.0-0.2.1
- projectportals-7.1.0-0.14.3
- projectworlds-7.1.0-0.13.0
- PTRLib-1.0.2
- RedstoneFlux-1.12-2.0.2.3-universal
- simplegenerators-1.12.2-2.0.15.1
- SimplyJetpacks2-1.12.2-2.2.8.56
- SolarFluxReborn_1.12.2-4.14r
- spongeforge-1.12.2-2705-7.1.0-BETA-3458
- ThermalDynamics-1.12.2-2.5.1.14-universal
- ThermalExpansion-1.12.2-5.5.0.29-universal
- ThermalFoundation-1.12.2-2.5.0.19-universal
- ThermalInnovation-1.12.2-0.3.0.7-universal
- valkyrielib-1.12.2-2.0.15.1
- VillagerShops-1.9

**Comment by Husky110** [comment]
The error occures in a Project Worlds Dimension with Type minecraft:overworld and generator sponge:void and doMobSpawn false, doDayLightCycle false.
Before I reinstalled my server and updated sponge and forge the shops worked great.

**Comment by Husky110** [comment]
Any update on the issue?

**Comment by DosMike** [comment]
not yet, I've been busy this week and probably won't be able to look into it tomorrow, but I'll get to it asap

**Comment by Husky110** [comment]
ah okay. My citybuild-server desperatly waits for the fix... ;)

**Comment by Husky110** [comment]
Heyho,
Any news on the issue?
