### ISSUE TITLE
Problem initializing plugin - SpongeVersion 1.12.2-2768-7.1.4

### ISSUE THREAD

**Issue by FROST-BR** [DosMike/VillagerShops#50]
When I try to start the server it appears this error, could you help me?

WARNING: coremods are present:
  SpongeCoremod (spongeforge-1.12.2-2768-7.1.4.jar)

Description: Exception in server tick loop

Missing Mods:
	unknown : need 1.3: have missing

net.minecraftforge.fml.common.MissingModsException: Mod vshop (VillagerShops) requires [langswitch@1.3]
	at net.minecraftforge.fml.common.Loader.sortModList(Loader.java:264)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:332)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Unknown Source)

**Comment by DosMike** [comment]
did you install langswitch version 1.3+?
also please do not forget to download the translation files from this git (see the [zip release](https://github.com/DosMike/VillagerShops/releases/tag/1.9.1) )

**Comment by FROST-BR** [comment]
The version I downloaded was the same, but I did not install the langswitch ... Is this a plugin? Thank you very much for your attention, desulpe my misunderstanding rsrs I am beginner ^^ !!

**Comment by FROST-BR** [comment]
Thank you :D !!!! Nice Work !!!!
